---
- name: Install and configure PostgreSQL on the VM
  hosts: database_hosts
  become: yes
  tasks:

    - name: Install PostgreSQL
      ansible.builtin.dnf:
        name: postgresql
        state: present
    
    - name: Install python db management
      ansible.builtin.dnf:
        name: python3-psycopg2
        state: present

    - name: Ensure PostgreSQL service is started and enabled
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Open Firewall Port
      ansible.posix.firewalld:
        service: postgresql
        permanent: yes
        state: enabled
