---
- name: Restore Data to Postgres
  hosts: rhel9-pgsql
  become: yes
  tasks:
    - name: add EPEL repo
      ansible.builtin.dnf:
        name: epel-release
        state: present
    - name: install restic
      ansible.builtin.dnf:
        name: restic
        state: present