---
- name: Restore Data to Postgres
  hosts: rhel9-pgsql
  become: yes

  tasks:
    - name: Add codeready builder repo
      community.general.rhsm_repository:
        name: codeready-builder-for-rhel-9-x86_64-rpms
        state: enabled
    - name: Import a key from a url
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    - name: add EPEL repo
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
    - name: install restic
      ansible.builtin.dnf:
        name: restic
        state: present
    - name:
      ansible.builtin.command:
        cmd: restic -r gs:restic-backups-rw8ns:/demo-todos-ext-postgres-backup restore latest --target /
      environment:
        GOOGLE_PROJECT_ID: 172836235953
        GOOGLE_APPLICATION_CREDENTIALS: /etc/gcp-secret
        RESTIC_PASSWORD_FILE: /etc/resic-secret

    - name: restart database
      ansible.builtin.service:
        name: postgresql
        state: restarted