---
- name: Restore Data to Postgres
  hosts: rhel9-pgsql
  become: yes
  tasks:
    - name: Add codeready buuilder repo
      rhsm_repository:
        name: codeready-builder-for-rhel-9-$(arch)-rpms
        state: enabled
    - name: add EPEL repo
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
    - name: install restic
      ansible.builtin.dnf:
        name: restic
        state: present