---
- name: Setup postgres Database
  hosts: rhel9-pgsql
  become: yes
  become_user: postgres
  tasks:
    - name: Ensure Database is available
      community.postgresql.postgresql_db:
        name: todos
        comment: "The ToDo App Database"
        state: present

    - name: Set db user 
      community.postgresql.postgresql_user:
        db: todos
        name: jws
        password: jws  # Choose a secure password here
    
    - name: configure remote access
      community.postgresql.postgresql_set:
        name: listen_addresses
        value: "*"

    - name: configure pg_hba.conf
      community.postgresql.postgresql_pg_hba:
        dest: /var/lib/pgsql/data/pg_hba.conf
        address: samenet
        contype: host
        users: jws
        create: true


    - name: Restart Database
      become_user: root
      ansible.builtin.service:
        name: postgresql
        state: restarted