---
- name: Start VM and configure PostgreSQL
  hosts: bigmachine
  become: yes
  tasks:
    - name: Ensure the VM is started
      community.libvirt.virt:
        name: rhel9-pgsql
        state: destroyed