---
collections:
  - name: community.libvirt
    version: 1.3.0
  - name: ansible.posix
    version: 1.5.4
  - name: community.postgresql
    version: 3.4.1
  - name: azure.azcollection
    version: 2.3.0
  - name: google.cloud
    version: 1.3.0  
  - name: community.general
    version: 9.0.1
